<?php

/**
 * @file
 * Primary module hooks for autocomplete_entity_display module.
 */

/**
 * Implements hook_form_alter().
 */
function autocomplete_entity_display_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // if (isset($form['field_tags'])) {}
  if (in_array($form_id, ['node_article_form', 'node_article_edit_form'])) {
    $form['#attached']['library'][] = 'autocomplete_entity_display/render_data';

    if ($entity = $form['field_tags']['widget']['target_id']['#default_value'][0]) {
      $description = strip_tags($entity->description->value);
      $form['field_tags']['#suffix'] = "<div id='tag-description'>Description: $description</div>";
    }
  }
}

/**
 * Implements hook_entity_view_alter().
 *
 * This hook implementation is cached. Changes require a cache rebuild.
 */
function autocomplete_entity_display_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  // if (isset($build['field_tags'])) {}
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'article') {
    $build['#attached']['library'][] = 'autocomplete_entity_display/render_data';

    if ($entity = $build['field_tags'][0]['#options']['entity']) {
      $description = strip_tags($entity->description->value);
      $build['field_tags']['#suffix'] = "<div id='tag-description'>Description: $description</div>";
    }
  }
}
